import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import { StringEnum } from "@earendil-works/pi-ai";
import { Type } from "typebox";
import { ScienceService, type Context } from "./src/service.ts";
import { loadConfig } from "./src/config.ts";

const id=Type.String({pattern:"^[a-zA-Z0-9_-]{1,128}$"});
const check=Type.Object({id:StringEnum(["json","csv","array","slit"] as const),parameters:Type.Record(Type.String(),Type.Unknown())},{additionalProperties:false});
const shared={request_id:id,profile:Type.Optional(Type.String()),timeout_seconds:Type.Optional(Type.Integer({minimum:1})),inputs:Type.Optional(Type.Array(Type.Object({source:Type.String(),path:Type.String()},{additionalProperties:false}))),expected_outputs:Type.Optional(Type.Array(Type.Object({path:Type.String(),required:Type.Boolean(),format:StringEnum(["json","csv","npy","binary"] as const),max_bytes:Type.Integer({minimum:1})},{additionalProperties:false}))),required_validations:Type.Optional(Type.Array(check))};
export default function scienceWorkbench(pi:ExtensionAPI){
  const service=new ScienceService();
  const context=(ctx:ExtensionContext):Context=>({cwd:ctx.cwd,session:ctx.sessionManager.getSessionId(),entry:ctx.sessionManager.getLeafId(),confirm:async(title,message)=>ctx.mode==="tui"?ctx.ui.confirm(title,message):false,reference:run=>pi.appendEntry("science-run",{run_id:run})});
  const restore=(ctx:ExtensionContext)=>{service.visible.clear();for(const entry of ctx.sessionManager.getBranch()){if(entry.type==="custom"&&entry.customType==="science-run"){const data=entry.data as {run_id?:string};if(data?.run_id)service.visible.add(data.run_id);}}};
  pi.on("session_start",async(_event,ctx)=>{await service.resetLifecycle();restore(ctx);});
  pi.on("session_tree",async(_event,ctx)=>{await service.resetLifecycle();restore(ctx);});
  pi.on("session_shutdown",async()=>{await service.resetLifecycle();});
  const result=async(value:unknown,cwd:string)=>{const limit=await loadConfig(cwd).then(c=>Math.min(c.limits.maxToolResultBytes,15000)).catch(()=>15000);const full=JSON.stringify(value);const text=Buffer.byteLength(full)>limit?JSON.stringify({summary:"Result exceeds inline limit. Use science_status with run_id and pagination.",run_id:(value as any)?.run_id??(value as any)?.run?.run_id}):full;return {content:[{type:"text" as const,text}],details:JSON.parse(text)};};
  pi.registerTool({name:"science_python",label:"Science Python",description:"Execute Python in a persistent, explicitly authorized local scientific kernel, or reset it. Not a sandbox. Outputs belong under artifacts/.",promptGuidelines:["Use science_python only for trusted scientific code; declare required_validations before execution and never automatically replay cells."],parameters:Type.Object({action:StringEnum(["execute","reset"] as const),...shared,code:Type.Optional(Type.String())},{additionalProperties:false}),async execute(_id,args,signal,_update,ctx){return result(await service.execute(context(ctx),"science_python",args,signal),ctx.cwd);}});
  pi.registerTool({name:"science_job",label:"Science Job",description:"Submit, poll, harvest or cancel an explicitly authorized scientific job. Query science_status for cached, offline state.",parameters:Type.Object({action:StringEnum(["submit","poll","harvest","cancel"] as const),...shared,run_id:Type.Optional(id),executable:Type.Optional(Type.String()),argv:Type.Optional(Type.Array(Type.String()))},{additionalProperties:false}),async execute(_id,args,signal,_update,ctx){return result(await service.execute(context(ctx),"science_job",args,signal),ctx.cwd);}});
  pi.registerTool({name:"science_artifact",label:"Science Verify",description:"Run bounded scientific validators and preserve evidence. Does not treat process exit success as scientific correctness.",parameters:Type.Object({action:StringEnum(["verify"] as const),request_id:id,run_id:id,profile:Type.Optional(Type.String()),checks:Type.Optional(Type.Array(check))},{additionalProperties:false}),async execute(_id,args,signal,_update,ctx){return result(await service.execute(context(ctx),"science_artifact",args,signal),ctx.cwd);}});
  pi.registerTool({name:"science_status",label:"Science Status",description:"Read cached local scientific run, artifact, kernel or log information. Never starts processes, contacts remote hosts or updates records.",parameters:Type.Object({action:StringEnum(["summary","runs","run","kernel","artifacts","log"] as const),run_id:Type.Optional(id),scope:Type.Optional(StringEnum(["branch","project"] as const)),stream:Type.Optional(StringEnum(["stdout","stderr"] as const)),offset:Type.Optional(Type.Integer({minimum:0})),limit:Type.Optional(Type.Integer({minimum:1,maximum:12000}))},{additionalProperties:false}),async execute(_id,args,_signal,_update,ctx){return result(await service.status(context(ctx),args),ctx.cwd);}});
  pi.registerCommand("science",{description:"Show cached scientific configuration and runtime status (read-only)",handler:async(_args,ctx)=>{ctx.ui.notify(JSON.stringify(await service.status(context(ctx),{action:"summary"}),null,2),"info");}});
}
