import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,lstat} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {ScienceService} from '../src/service.ts';
import {loadConfig} from '../src/config.ts';
import {Store} from '../src/store.ts';
async function fixture(t){const root=await mkdtemp(path.join(os.tmpdir(),'science-test-'));await mkdir(path.join(root,'.pi'));await writeFile(path.join(root,'.pi/science-workbench.json'),JSON.stringify({schemaVersion:1,defaultProfile:'local',profiles:{local:{transport:'local',python:'/usr/bin/python3',executionTrust:'trusted-host',environmentAllowlist:[]}},limits:{maxSubmissionsPerGrant:50}}));const service=new ScienceService();t.after(async()=>{await service.resetLifecycle();await rm(root,{recursive:true,force:true});});return {root,service,ctx:{cwd:root,session:'test',entry:null,confirm:async()=>true,reference:()=>{}}};}
test('idle status never creates runtime data',async t=>{const {root,service,ctx}=await fixture(t);await service.status(ctx,{action:'summary'});await assert.rejects(lstat(path.join(root,'.science')),{code:'ENOENT'});});
test('persistent kernel, provenance, idempotency and reset',async t=>{const {service,ctx,root}=await fixture(t);const first={action:'execute',request_id:'one',code:'value = 41\nprint(value)'};const a=await service.execute(ctx,'science_python',first);assert.equal(a.execution_status,'succeeded');assert.equal(a.completion_status,'unverified');const b=await service.execute(ctx,'science_python',{action:'execute',request_id:'two',code:'print(value + 1)'});assert.equal(b.kernel_instance_id,a.kernel_instance_id);assert.match(await readFile(path.join(root,'.science/runs',b.run_id,'logs/stdout.log'),'utf8'),/42/);assert.equal((await service.execute(ctx,'science_python',first)).run_id,a.run_id);await assert.rejects(service.execute(ctx,'science_python',{...first,code:'value=0'}),/idempotency_conflict/);await service.resetLifecycle();await assert.rejects(service.execute(ctx,'science_python',{action:'execute',request_id:'three',code:'print(value)'}),/failed/);});
test('output integrity and scientific validation',async t=>{const {service,ctx}=await fixture(t);const m=await service.execute(ctx,'science_python',{action:'execute',request_id:'data',code:'from pathlib import Path\nPath("artifacts/value.json").write_text("{\\"value\\":42}")',expected_outputs:[{path:'value.json',required:true,format:'json',max_bytes:100}],required_validations:[{id:'json',parameters:{path:'artifacts/value.json',fields:['value'],equals:{value:42}}}]});assert.equal(m.artifact_status,'complete');const v=await service.execute(ctx,'science_artifact',{action:'verify',request_id:'verify',run_id:m.run_id});assert.equal(v.run.completion_status,'verified');});
test('missing output is rejected without falsifying exit status',async t=>{const {service,ctx}=await fixture(t);const m=await service.execute(ctx,'science_python',{action:'execute',request_id:'missing',code:'pass',expected_outputs:[{path:'absent',required:true,format:'binary',max_bytes:10}]});assert.equal(m.execution_status,'succeeded');assert.equal(m.artifact_status,'incomplete');assert.equal(m.completion_status,'rejected');});
test('timeout invalidates kernel and leaves evidence',async t=>{const {service,ctx}=await fixture(t);await assert.rejects(service.execute(ctx,'science_python',{action:'execute',request_id:'timeout',code:'import time\ntime.sleep(60)',timeout_seconds:1}),/timed_out/);const runs=await new Store(ctx.cwd).list();assert.equal(runs[0].execution_status,'timed_out');});
test('authorization denial does not create records',async t=>{const {service,ctx,root}=await fixture(t);ctx.confirm=async()=>false;await assert.rejects(service.execute(ctx,'science_python',{action:'execute',request_id:'denied',code:'pass'}),/approval_required/);await assert.rejects(lstat(path.join(root,'.science')),{code:'ENOENT'});});
test('config rejects unknown fields and unsafe profiles',async t=>{const {root}=await fixture(t);const file=path.join(root,'.pi/science-workbench.json');const c=JSON.parse(await readFile(file));c.profiles.local.environmentAllowlist=['OPENAI_API_KEY'];await writeFile(file,JSON.stringify(c));await assert.rejects(loadConfig(root),/sensitive_environment_rejected/);});
test('local asynchronous job and cached status',async t=>{const {service,ctx}=await fixture(t);const m=await service.execute(ctx,'science_job',{action:'submit',request_id:'job',executable:'/usr/bin/python3',argv:['-c','print(123)']});let status;for(let i=0;i<100;i++){status=await service.status(ctx,{action:'run',run_id:m.run_id});if(status.execution_status!=='running')break;await new Promise(r=>setTimeout(r,25));}assert.equal(status.execution_status,'succeeded');assert.match((await service.status(ctx,{action:'log',run_id:m.run_id})).text,/123/);});
